service: holewinskidev
image: erwijet/holewinskidev

servers:
  - web-1 # tailscale

proxy:
  ssl: false
  hosts:
    - www.holewinski.dev
  app_port: 80
  healthcheck:
    path: /

registry:
  username: erwijet
  password: [KAMAL_REGISTRY_PASSWORD]

builder:
  arch: amd64
