events {
    worker_connections 1024;
}

http {

  include mime.types;
  sendfile on;

  server {
    listen 3000;
    listen [::]:3000;

    autoindex off;
    server_name _;
    server_tokens off;

    root /var;
    index resume.pdf;
  }
}
