export const SITE = {
  website: "https://www.holewinski.dev",
  author: "Tyler Holewinski",
  profile: "https://www.holewinski.dev",
  desc: "Tyler's personal website",
  title: "holewinski.dev",
  ogImage: "banner.png",
  postPerIndex: 4,
  postPerPage: 4,
  showArchives: true,
  dynamicOgImage: true,
  showBackButton: true,
  shame: true,
  dir: "ltr",
  lang: "en",
  timezone: "America/New_York",
  bios: [
    "Bookbinder",
    "Pothos Gardener",
    "Aspiring Chef",
    "z80 Nostalgist",
    "Personal Library Builder",
  ],
} as const;
